name: feature_test

on:
  push:
    branches: [ "feature_test" ]
  pull_request:
    branches: [ "feature_test" ]

  workflow_dispatch:

jobs:
  windows_PWSH:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3

      # Step to upload module to PSGallery
      - name: Test ScriptUtils commands Windows PWSH
        shell: pwsh
        run: |
          Import-Module ./ScriptUtils
          Get-PSInfo
          
  ubuntu_PWSH:
    runs-on: ubuntu-latest
    needs: windows_PWSH
    
    steps:
      - uses: actions/checkout@v3

      # Step to upload module to PSGallery
      - name: Test ScriptUtils commands Ubuntu PWSH
        shell: pwsh
        run: |
          Import-Module ./ScriptUtils
          Get-PSInfo
          
  MACOS_PWSH:
    runs-on: macos-latest
    needs: ubuntu_PWSH
    
    steps:
      - uses: actions/checkout@v3

      # Step to upload module to PSGallery
      - name: Test ScriptUtils commands Windows PWSH
        shell: pwsh
        run: |
          Import-Module ./ScriptUtils
          Get-PSInfo
          
  windows_powershell_native:
    runs-on: windows-latest
    needs: MACOS_PWSH
    
    steps:
      - uses: actions/checkout@v3

      # Step to upload module to PSGallery
      - name: Test ScriptUtils commands Windows PowerShell
        shell: powershell
        run: |
          Import-Module ./ScriptUtils
          Get-PSInfo
