name: feature_test

on:
  push:
    branches: [ "feature_test" ]
  pull_request:
    branches: [ "feature_test" ]

  workflow_dispatch:

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3

      # Step to upload module to PSGallery
      - name: Test ScriptUtils commands
        shell: pwsh
        run: |
          Get-ChildItem ./ -Recurse | select fullname
          Import-Module ./ScriptUtils
          Get-SubnetFormat "32"
          Get-SubnetFormat "255.255.255.128"
          Get-SubnetFormat 0.0.0.127
          Repair-FileName "File1/"
          Test-FileName "File1/"
          Test-Ipv4AddressFormat "192.168.1.1"
          Test-Ipv4AddressFormat "192.168.1.abs"
          Get-PSInfo
