name: Publish_ScriptUtils_module_Using_PSCommand

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      # Step to upload module to PSGallery
      - name: Publish PS Module directly via command
        shell: powershell
        env:
          NuGet_ApiKey: ${{ secrets.PS_GALLERY_KEY }}
        run: |
          (Get-Item .\).fullname
          Get-ChildItem D:\ -Recurse | select FullName, LastWriteTime | ft -AutoSize -Wrap
#          Publish-Module -Path ./ScriptUtils -NuGetApiKey "NuGet_ApiKey" -Repository PSGallery -Verbose
